  version: '3.1'
  services:
    app:
      build: .
      image: 'neon-application'
      container_name: neon-app-container
      ports:
        - "8080:8080"
      depends_on:
        database:
          condition: service_healthy
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      networks:
        - service-network

    database:
      image: postgres
      container_name: db-compose-container
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=neon-db
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - service-network

  networks:
    service-network:
      driver: bridge
