  version: '3.1'
  services:
    app:
      build: .
      image: 'neon-application'
      container_name: neon-app-container
      ports:
        - "8080:8080"
      depends_on:
        database:
          condition: service_healthy
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      networks:
        - my-network

    database:
      image: postgres
      container_name: db-compose-container
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=neon-db
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - my-networkx

    elk:
      image: sebp/elk
      container_name: neon-elk-container
      ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"
      environment:
        - ES_HEAP_SIZE=1g
        - LS_HEAP_SIZE=256m
      volumes:
        - ./logstash:/etc/logstash/conf.d/
      networks:
        - my-network

  networks:
    my-network:
      driver: bridge
